name: opak_fuar
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0
  xml: ^6.3.0
  math_expressions: ^2.4.0
  get: ^4.6.5
  intl: ^0.17.0
  device_info_plus: ^9.1.1
  simple_barcode_scanner: ^0.0.8
  google_fonts: ^6.1.0
  printing: ^5.11.1
  money_formatter: ^0.0.3
  uuid: ^3.0.7
  dropdown_search: ^5.0.6
  image_picker: ^0.8.7+1
  htmltopdfwidgets: ^0.0.9+2
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf    

